name: PR Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pdm config python.use_venv false && pdm install -G :all
      - name: patch secret key
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: cat ssrando.py.in | envsubst > ssrando.py
      # - name: Test if the formatting is correct
      #   run: black . --check
      - name: Run tests
        run: python3 -mpytest test/test_placement_file.py
      - name: Build distribution
        run: python3 -mPyInstaller ssrando.spec
      - name: Run tests
        run: |
          python3 randoscript.py --noui --dry-run --seed=0
          cp -r logs logs_source
          dist/ssrando --noui --dry-run --seed=0
          diff logs logs_source
      - name: Make arc-replacements folder
        run: |
          mkdir -p dist/arc-replacements
          cp arc-replacements/README.md dist/arc-replacements
        shell: bash
      - name: Copy Readme and changelog
        run: cp README.md CHANGELOG.md dist
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: dist ${{ matrix.os }}
          path: dist
